// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2, arg3, arg4);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function ForceStartMonitor(arg1) {
  return window['go']['main']['App']['ForceStartMonitor'](arg1);
}

export function GetPlaintext(arg1) {
  return window['go']['main']['App']['GetPlaintext'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function RequestSwitch(arg1) {
  return window['go']['main']['App']['RequestSwitch'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function StopMonitor() {
  return window['go']['main']['App']['StopMonitor']();
}

export function TogglePause() {
  return window['go']['main']['App']['TogglePause']();
}
