// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {logic} from '../models';

export function AddAccount(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function DeleteAccount(arg1:string):Promise<string>;

export function ExportBackup():Promise<string>;

export function ForceStartMonitor(arg1:logic.Account):Promise<string>;

export function GetPlaintext(arg1:string):Promise<string>;

export function GetSettings():Promise<logic.ConfigData>;

export function RequestSwitch(arg1:logic.Account):Promise<string>;

export function SaveTheme(arg1:string):Promise<string>;

export function StopMonitor():Promise<string>;

export function TogglePause():Promise<string>;
