// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddAccount'](arg1, arg2, arg3, arg4);
}

export function CalibrateZZZPoints() {
  return window['go']['main']['App']['CalibrateZZZPoints']();
}

export function CaptureDebugWindow(arg1) {
  return window['go']['main']['App']['CaptureDebugWindow'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function ExecuteLoginAction(arg1, arg2) {
  return window['go']['main']['App']['ExecuteLoginAction'](arg1, arg2);
}

export function ExportBackup() {
  return window['go']['main']['App']['ExportBackup']();
}

export function GetMonitorStatus() {
  return window['go']['main']['App']['GetMonitorStatus']();
}

export function GetPlaintext(arg1) {
  return window['go']['main']['App']['GetPlaintext'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function IsGameRunning(arg1) {
  return window['go']['main']['App']['IsGameRunning'](arg1);
}

export function PrepareAccountEnvironment(arg1) {
  return window['go']['main']['App']['PrepareAccountEnvironment'](arg1);
}

export function SaveAccountsOrder(arg1) {
  return window['go']['main']['App']['SaveAccountsOrder'](arg1);
}

export function SaveGamePaths(arg1) {
  return window['go']['main']['App']['SaveGamePaths'](arg1);
}

export function SaveTheme(arg1) {
  return window['go']['main']['App']['SaveTheme'](arg1);
}

export function SelectGameFile() {
  return window['go']['main']['App']['SelectGameFile']();
}

export function StartGame(arg1) {
  return window['go']['main']['App']['StartGame'](arg1);
}

export function StartMonitor(arg1) {
  return window['go']['main']['App']['StartMonitor'](arg1);
}

export function StopMonitor() {
  return window['go']['main']['App']['StopMonitor']();
}

export function TogglePauseMonitor() {
  return window['go']['main']['App']['TogglePauseMonitor']();
}

export function UpdateAccount(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateAccount'](arg1, arg2, arg3, arg4);
}
